global using static Finanzas.Extensions.ContextData;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Finanzas.Interfaces;
global using Finanzas.Models;
global using System.Collections.ObjectModel;
global using Finanzas.ViewModels;
global using CommunityToolkit.Mvvm.Messaging.Messages;
global using Finanzas.Extensions;
global using Finanzas.Services;
global using CommunityToolkit.Maui;
global using Finanzas.Pages;
global using Microsoft.Extensions.Logging;